config/routes.rb
Rails.application.routes.draw do

  # This is the page your app will display when you go to the root URL
  root 'site#index' # this uses the "#" notation
  get 'site/index'  # this uses the "/" notation - it's interchangeable with the one above

  # These are the routes used to manage users
  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"

  # go to this video here: https://www.youtube.com/watch?v=UAvuo-EbTFY
  # look at this part of the video: 6:12 / 56:18 (timestamp)
  # at the 6:51 mark, Avi sets the "Authorization callback URL" (in his newly created OAuth GitHub app) to the following:
  # http://localhost:3000/auth/github/callback
  # the get request below must match the "Authorization callback URL" you specify in the GitHub OAuth app.
  get '/auth/:provider/callback' => 'sessions#create'

  # route for search bar in index.html.erb in /events
  get '/search' => "events#index"



  # You can create a new OAuth (same thing as OmniAuth) on GitHub by going here: https://github.com/settings/developers

  # The second part of this OmniAuth business is to go to this directory: config/initializers
  # and create a file called "omniauth.rb"
  # WARNING WARNING WARNING - this "omniauth.rb" file will contain sensitive data, so if you haven't done so already, you first need to create
  # a ".gitignore" file in the root directory and then specifically include this file: config/initializers/omniauth.rb
  # INFO INFO INFO - If you're using this Rails app as a starting point for your Rails project, relax, the ".gitignore" has already been created for you,
  # and it includes the "config/initializers/omniauth.rb" - this means no sensitive data will be compromised.

  # In this project there is a file here: config/initializers/omniauth_boilerplate.rb
  # Go there next & follow instructions to setup OmniAuth-GitHub

  # resources :users

  # This route grabs the homepage for the actual app you're building

  get '/homeapp' => "site#homeapp"

  get '/auth/:provider/callback' => 'sessions#create'

  resources :users do
    resources :registrations, only: [:show, :index, :edit, :new]
  end
  
  resources :events, only: [:index, :show]

  resources :registrations

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, :presence => true
  validates :username, presence: true

  validates :email, uniqueness: { case_sensitive: false }
  validates :username, uniqueness: { case_sensitive: false }

  has_many :registrations
  has_many :events, through: :registrations

  # scope :max_registrations, -> {order("registrations DESC").limit(1)}

  # scope :max_registrations, -> {order(registrations: :desc).limit(1)}

 # scope :max_registrations, -> {User.limit(1).order(registrations: :desc)}

  # scope :most_registrations, -> {order(registrations: :desc).limit(1)}
  # scope :most_registrations, -> {order(registrations: :desc)} 

  # scope :most_registrations, -> {User.joins(:registrations).group("users.id").order("count(users.id) DESC").limit(1)} 

  # scope :most_registrations, -> {User.joins("left join registrations on registrations.user_id = users.id").group("users.id").order("count(users.id) DESC")}

  # --------
  
  # The method below is returning what I want in the console : tested this out in the console as:
  
  # User.joins(:registrations)
  # User.joins(:regisrtations).group("users.id")
  # User.joins(:regisrtations).group("users.id").order("count(users.id) DESC").limit(1)
 
  # But when I ran the method as below, i received errors on the console
  scope :most_registrations, ->  {User.joins(:registrations).group("user.id").order("count(user.id) DESC").limit(1)}

  # tried to redo the scope above as class method but was also not working
  # def self.most_registrations
  #   User.joins(:registrations).group("user.id").order("count(user.id) DESC").limit(1)
  # end

  # This method gets created here:
  # https://www.youtube.com/watch?v=UAvuo-EbTFY (38:00 / 56:18)
  # The "auth_hash" below is set to the value of request.env["omniauth.auth"]
  # in the sessions controller's create action.
  def self.find_or_create_by_omniauth(auth_hash)
    # The "first_or_create" ActiveRecord method will find the first instance
    # where the user's username is the same as the [:info][:name] value inside
    # the auth_hash.  If no such name exists, ActiveRecord will create a new user.
    # "first_or_create" will always return an instance of a user.
    self.where(:username => auth_hash["info"]["name"]).first_or_create do |user|
      # This user is using OmniAuth.  Here we assume they will never need to login
      # to this Rails app using the non-OmniAuth [standard] login means.  To that end,
      # an OmniAuth user will never enter a password on this Rails app (only on GitHub)
      # and so on the next line of code below, we need to assign them a password
      # because the User.rb model requires all users to have such a password.
      # "SecureRandom.hex" will assign a number that hackers won't be able to guess
      user.password = SecureRandom.hex,
      if auth_hash["info"]["email"] == nil # that is, no email address is listed.
        # some GitHub users have their email set to private.  If that is the
        # case, the user's email address will be set to this value below:
        user.email = "unknown: GitHub doesn't share this user's email"
      else # if the user's GitHub account has a public email address...
        # the user's email address in this app will be the same as their GitHub
        # email address.
        user.email = auth_hash["info"]["email"]
      end
    end
  end

  def display_full_name
    self.first_name + " " + self.last_name
  end

  # helper method to refactor view

  def last_updated
      updated_at.strftime("Last updated %A, %b %e, at %l:%M %p")
  end


  # User.all 

  # def self.users_with_max_registrations
  #     @user = User.where('max(:events)')
  # end

  # def self.events
  #   where()
  # end

  # Scope level method - class method to find the user with the most registrations
  # first find the 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # This will place the "Home" and "Logout" links at the bottom of each page:
  layout "app_layout"
  # If you are already home then you will only see "Logout"
  # If you are already logged out you will only see "Home"
  # and is located here: app/views/layouts/app_layout.html.erb

  def index
    @users = User.all

    # below code for scope method
    @user_most_registrations = User.most_registrations 
    # @user_most_registrations = @users.most_registrations
  end

  def show 
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.username = params[:user][:username]
    @user.password = params[:user][:password]
    if @user.valid?
      @user.save
      session[:user_id] = @user.id

      redirect_to user_path(@user) # go to user show page
      # redirect_to root_path
    else
      render :new
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update

    @user = User.find(params[:id])
    
    if @user.update(user_params(:password))
        redirect_to user_path(@user)
    else
        render :edit
    end

  end

  def destroy
      
  end

  def user_params(*args)
      params.require(:user).permit(*args)
  end

end

app/views/users/_form.html.erb
<style>
      
body {
  text-align: center;
}

</style> 

<%= form_for(@user) do |u| %> 


    <% if @user.errors.any? %>
        <div class="field_with_error" style="color:red; font-size:14px">
            <h2>
                <%= pluralize(@user.errors.count, "error") %>
                prohibited this user from being saved:
            </h2>

            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li style="list-style-type:none;"><%= msg %></li>
                <% end %>
            </ul>
        </div>

    <% end %>
    
    <div style = "font-size: 16px">
        <%= u.label :email %>
        <%= u.text_field :email %><br>

        <%= u.label :username %>
        <%= u.text_field :username %><br>

        <%= u.label :password %>
        <%= u.password_field :password %><br>
    </div>

    <%= u.submit %>

<% end %>
<br>
<div style="font-size: 12px">
    <p><u>To successfully save your user data, be sure to: </u></p>
    <p>1. Have a minimum of 1 character for the first and last name</p>
    <p>2. A unique email address (if email is taken by another user, you must enter a email that has not been taken)</p>
    <p>3. The user name must be between 4 to 12 characters</p>
    <p>4. The password must be between 5 to 25 characters long</p>
</div>

app/views/users/edit.html.erb
<u><h2>Edit User Account<h2></u>

<div style="font-size:14px">
    <%= link_to "My Homepage", current_user%> <br><br>
</div>

<p style="color:red; font-size:13px">
    <i>
        Username and email address cannot be updated. If you input new username and email address, the information will not be saved.
    </i>
</p>

<%= render 'form' %>

app/views/users/index.html.erb
<style>

    div {
        text-align: center;
    }

</style>

<div>

    <h3>There are currently <u style = "color: red;"><%= @users.count %></u> users registerd</h3>



    <div style="font-size: 14px">
        <i>
            Logged in user is only authorized to add other users to volunteer assignment. <br>
            Logged in user is not allowed to change any personal information of other users. <br>
            Logged is user is only allowed to change their own personal information. <br>
        </i>
    </div>

    <br>

    <p><b> <u>User with Most Registrations </u></b></p>

    # view code for scope method 
    <%=  @user_most_registrations %> 

    <u><h4>CURRENT USERS</h4></u>

</div>

<table border="3" align = "center">
    <tr>
        <th> Username </th>

    </tr>

        <tr>

        <td>
            <% @users.each do |user| %> 
                <!-- <%= link_to user.username, user_path(user)%> -->
                <%= user.username %>
                <br>
            <% end %>   
        </td>

    </tr>

    <br>

</table>

app/views/users/new.html.erb
<h2>Create New User Account<h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username%>!</h1><br><br>


<br>

<div style="border:3px; border-style:solid; border-color:#FF0000; padding: 2em;">
    <p>You are currently logged in as <%= current_user.username %>. Click <%= link_to "Edit", edit_user_path(@user) %> to edit your profile</p> 

    <p>Your user's email address is: <u style="color:blue"><%= @user.email %></u></p>

    <em>Your personal information was last updated at : <%= @user.last_updated %> </em></p>
    
    <br>
        <p><%= link_to "ALL REGISTRATIONS", "/registrations" %></p>
    <br>
    
    <h3>The number of event(s) you are currently volunteering for: <strong style = "color : red"><%= @user.registrations.count %></strong></h3>

    <p>Click <%= link_to "here", new_user_registration_path(@user) %> to register yourself or another user to volunteer for an event</p>
    
    <p><strong>Below are the events you are currently registered for:</strong><p>

    
    
    <table border="3">
        <tr>
            <th> Event Name </th>
            <th> Event Date </th>
            <th> Update Registration</th>
        </tr>
    
            <tr>
    
            <td>
                <% @user.registrations.each do |registration| %> 
                    <%= registration.event.name %>
                    <br>
                <% end %>     
            </td>
                
            <td>
                <% @user.registrations.each do |registration| %> 
                    <%= registration.event.date%>
                    <br>
                <% end %>
            </td>
    
            <td>
                <% @user.registrations.each do |registration| %> 
                    <!-- Depending on whether the below edit_user_registration_path gives correct URL, keep it / remove it -->
                    <%= link_to "Edit", edit_registration_path(registration) %>
                    <br>
                <% end %>
            </td>
    
        </tr>
    
        <br>
    
    </table>

    <br>
</div>