config/routes.rb
Rails.application.routes.draw do

  # This is the page your app will display when you go to the root URL
  root 'site#index' # this uses the "#" notation
  get 'site/index'  # this uses the "/" notation - it's interchangeable with the one above

  # These are the routes used to manage users
  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"

  # go to this video here: https://www.youtube.com/watch?v=UAvuo-EbTFY
  # look at this part of the video: 6:12 / 56:18 (timestamp)
  # at the 6:51 mark, Avi sets the "Authorization callback URL" (in his newly created OAuth GitHub app) to the following:
  # http://localhost:3000/auth/github/callback
  # the get request below must match the "Authorization callback URL" you specify in the GitHub OAuth app.
  get '/auth/:provider/callback' => 'sessions#create'

  # route for search bar in index.html.erb in /events
  get '/search' => "events#index"



  # You can create a new OAuth (same thing as OmniAuth) on GitHub by going here: https://github.com/settings/developers

  # The second part of this OmniAuth business is to go to this directory: config/initializers
  # and create a file called "omniauth.rb"
  # WARNING WARNING WARNING - this "omniauth.rb" file will contain sensitive data, so if you haven't done so already, you first need to create
  # a ".gitignore" file in the root directory and then specifically include this file: config/initializers/omniauth.rb
  # INFO INFO INFO - If you're using this Rails app as a starting point for your Rails project, relax, the ".gitignore" has already been created for you,
  # and it includes the "config/initializers/omniauth.rb" - this means no sensitive data will be compromised.

  # In this project there is a file here: config/initializers/omniauth_boilerplate.rb
  # Go there next & follow instructions to setup OmniAuth-GitHub

  # resources :users

  # This route grabs the homepage for the actual app you're building

  get '/homeapp' => "site#homeapp"

  get '/auth/:provider/callback' => 'sessions#create'

  resources :users do
    resources :registrations, only: [:show, :index, :edit, :new]
  end
  
  resources :events, only: [:index, :show]

  resources :registrations

end

app/models/event.rb
class Event < ActiveRecord::Base

    has_many :registrations
    has_many :users, through: :registrations

    # find all of the events that have a name whatever the argument is
    # scope :event -> (event_name) {search_item(event_name)}
    # ? in SQL is placeholder

    # look up turbo links and figure hout how to work with them (how to disable them ni rails 6)

    scope :search_item, -> (event_name) { where("name LIKE ? ", "%#{event_name}%")}

end 

app/controllers/events_controller.rb
class EventsController < ApplicationController

    layout "app_layout"
    # Events controller complete. Only 2 methods will be required for this controller

    def index
        
        # note: turbo links -> helps load pages faster, but sometimes does not 

        # if the params[:q] exists we do a search 
            if (params[:q])
                @events = Event.search_item(params[:q])
        # else , return all of the events
            else
                @events = Event.all
            end
    end

    def show 
        @event = Event.find(params[:id])
    end

    def event_params
        params.permit(:q)
    end

end

app/views/events/index.html.erb
<style>

  table {
    border-collapse: collapse;
  }

  td, th {
    border: 4px solid;
    text-align: left;
    padding: 8px;
  }

</style>

<h1>List of Hackathon Events</h1><br>

  <%= form_with(url: "/search", method: "get") do %>
    <%= label_tag(:q, "Search Events") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
  <% end %>

<p><em>Below is a list of upcoming hackathon events. Dates are subject to change.</em></p>

<table>
  
  <tr>
    <th>Event Name</th>
    <th>Event Date</th>
    <th>Event Location</th>
    <th>Event Description</th>
  </tr>

  <tr>
  
  <td>
    <% @events.each do |event| %>
    <%= link_to event.name, event_path(event) %> 
    <br>
    <% end %>
  </td>
  
  <td>
    <% @events.each do |event| %>
    <%=  event.date %> 
    <br>
    <% end %>
  </td>

  <td>
    <% @events.each do |event| %>
    <%=  event.location %> 
    <br>
    <% end %>
  </td>

  <td>
    <% @events.each do |event| %>
    <%=  event.description %> 
    <br>
    <% end %>
  </td>

  </tr>
  
  
</table>

app/views/events/show.html.erb
<br>
<br>
<%= link_to "ALL EVENTS", "/events"%> <br><br>

<h2>Hackathon Event Details</h2><br>

<b>Event Name:</b> <%= @event.name %><br><br>
<b>Event Date:</b> <%= @event.date %><br><br>
<b>Event Location:</b> <%= @event.location %><br><br>
<b>Event Description:</b> <%= @event.description %><br><br>