config/routes.rb
Rails.application.routes.draw do

  # This is the page your app will display when you go to the root URL
  root 'site#index' # this uses the "#" notation
  get 'site/index'  # this uses the "/" notation - it's interchangeable with the one above

  # These are the routes used to manage users
  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"

  # go to this video here: https://www.youtube.com/watch?v=UAvuo-EbTFY
  # look at this part of the video: 6:12 / 56:18 (timestamp)
  # at the 6:51 mark, Avi sets the "Authorization callback URL" (in his newly created OAuth GitHub app) to the following:
  # http://localhost:3000/auth/github/callback
  # the get request below must match the "Authorization callback URL" you specify in the GitHub OAuth app.
  get '/auth/:provider/callback' => 'sessions#create'

  # route for search bar in index.html.erb in /events
  get '/search' => "events#index"



  # You can create a new OAuth (same thing as OmniAuth) on GitHub by going here: https://github.com/settings/developers

  # The second part of this OmniAuth business is to go to this directory: config/initializers
  # and create a file called "omniauth.rb"
  # WARNING WARNING WARNING - this "omniauth.rb" file will contain sensitive data, so if you haven't done so already, you first need to create
  # a ".gitignore" file in the root directory and then specifically include this file: config/initializers/omniauth.rb
  # INFO INFO INFO - If you're using this Rails app as a starting point for your Rails project, relax, the ".gitignore" has already been created for you,
  # and it includes the "config/initializers/omniauth.rb" - this means no sensitive data will be compromised.

  # In this project there is a file here: config/initializers/omniauth_boilerplate.rb
  # Go there next & follow instructions to setup OmniAuth-GitHub

  # resources :users

  # This route grabs the homepage for the actual app you're building

  get '/homeapp' => "site#homeapp"

  get '/auth/:provider/callback' => 'sessions#create'

  resources :users do
    resources :registrations, only: [:show, :index, :edit, :new]
  end
  
  resources :events, only: [:index, :show]

  resources :registrations

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  # this will specify to use the formatting in app/views/layouts/app_layout.html.erb
  layout "app_layout"

  def index
    # @user = User.find(params[:user_id])
    # render :plain => "This is the startpoint of the site"
    if current_user
      @user = current_user
      # render :plain => "a user is logged in"
      redirect_to user_path(@user)
      # render 'homeapp'
    end
  end

  def homeapp
    if !current_user
      redirect_to root_path
    end
  end
end

app/views/site/index.html.erb
<style>
  .appinfo, .login, .noaccount{
      width: 550px;
      border: 2px solid red;
  }

</style>

  <h2>Tech Event Registration App</h2>

  <p>User do not need an account to do the following:</p>
    <div class = "noaccount">
      <ul>
        <li><%= link_to "View all registered users", users_path %> </li>
        <li><%= link_to "List of events users allowed to register for", events_path %></li>
      </ul>
    </div>

<p>Registered users are allowed to interact with authentication & authorization functionalities</p>

  <div class="appinfo">
    <ul>

      <p><b>AUTHENTICATION</b></p>

      <li>Users create a new account</li>
      <li>Users login with the created account <b>OR</b> login using GitHub OmniAuth</li>
      
      <p><b>AUTHORIZATION</b></p>
      
      <li>Users may view list of all of the tech events</li>
      <li>Users may view details of individual Tech events</li>
      <li>Users may register to volunteer for a tech event</li>
      <li>Users may also register other users to voluteer for a tech event</li>
      <li>Users may view all registrations</li>
      <li>Users may edit their profile information only</li>
      <li>Users may edit their specific registrations only</li>
    </ul>
  </div>

  <p>Please sign up or login below to use the application:</p>

<div class="login">
  <ul>
    <li><%= link_to "Signup as a new user", new_user_path %></li>
    <li><%= link_to "Login as an existing user", login_path %></li>
  </ul>
</div>