config/routes.rb
Rails.application.routes.draw do

  # This is the page your app will display when you go to the root URL
  root 'site#index' # this uses the "#" notation
  get 'site/index'  # this uses the "/" notation - it's interchangeable with the one above

  # These are the routes used to manage users
  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"

  # go to this video here: https://www.youtube.com/watch?v=UAvuo-EbTFY
  # look at this part of the video: 6:12 / 56:18 (timestamp)
  # at the 6:51 mark, Avi sets the "Authorization callback URL" (in his newly created OAuth GitHub app) to the following:
  # http://localhost:3000/auth/github/callback
  # the get request below must match the "Authorization callback URL" you specify in the GitHub OAuth app.
  get '/auth/:provider/callback' => 'sessions#create'

  # route for search bar in index.html.erb in /events
  get '/search' => "events#index"



  # You can create a new OAuth (same thing as OmniAuth) on GitHub by going here: https://github.com/settings/developers

  # The second part of this OmniAuth business is to go to this directory: config/initializers
  # and create a file called "omniauth.rb"
  # WARNING WARNING WARNING - this "omniauth.rb" file will contain sensitive data, so if you haven't done so already, you first need to create
  # a ".gitignore" file in the root directory and then specifically include this file: config/initializers/omniauth.rb
  # INFO INFO INFO - If you're using this Rails app as a starting point for your Rails project, relax, the ".gitignore" has already been created for you,
  # and it includes the "config/initializers/omniauth.rb" - this means no sensitive data will be compromised.

  # In this project there is a file here: config/initializers/omniauth_boilerplate.rb
  # Go there next & follow instructions to setup OmniAuth-GitHub

  # resources :users

  # This route grabs the homepage for the actual app you're building

  get '/homeapp' => "site#homeapp"

  get '/auth/:provider/callback' => 'sessions#create'

  resources :users do
    resources :registrations, only: [:show, :index, :edit, :new]
  end
  
  resources :events, only: [:index, :show]

  resources :registrations

end

app/views/layouts/app_layout.html.erb
<!DOCTYPE html>
<html>

  <!-- The default layout is here: -->
  <!-- app/views/layouts/application.html.erb -->
  <!-- this layout is specific to the this app -->
  <head>
    <title>User Registration</title>
    <!-- without the csrf tag you will get authenticity errors -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- this line of code is not used in this app because itt currently has no javascript -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- this will utilize styles in: app/assets/stylesheets/application.css -->
    <!-- without this line of code, text fields incorrectly populated [or left blank] will not show up as red -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <img src="https://wiki.eclipse.org/images/9/96/ECNA2016_Hackathon_logo_final_coloredit1.png" alt="no image" width="200px" height="100px">
    <%= yield %>
  </body>

  <br>

  <footer>
    <center>
      <% if !current_page?(root_path) %>
      <%= link_to "Home", root_path %><br><br>
      <% end %>
      <% if current_user %>
        <%= link_to "Logout", logout_path %>
      <% end %>
    </center>
  </footer>
</html>